#  DPFS-License-Identifier: BSD-3-Clause
#  Copyright (C) 2025 Libr Corporation.
#  All rights reserved.
#
DPFS_ROOT_DIR := $(abspath $(CURDIR)/../..)


SPDK_ROOT_DIR := $(abspath $(CURDIR)/../../thirdparty/spdk)
include $(SPDK_ROOT_DIR)/mk/spdk.common.mk
include $(SPDK_ROOT_DIR)/mk/spdk.modules.mk

CXXFLAGS += -I$(DPFS_ROOT_DIR)/include
SO_VER := 1
SO_MINOR := 0

CXX_SRCS = spdkcontrol.cpp 
LIBNAME = storage

SPDK_MAP_FILE = $(abspath $(CURDIR)/spdk_blob.map)

# include $(SPDK_ROOT_DIR)/mk/spdk.lib.mk
include $(SPDK_ROOT_DIR)/mk/spdk.deps.mk